pegasystems/pega-helm-charts

README.md, charts/pega/.helmignore, charts/pega/Chart.yaml, charts/pega/config/prconfig.xml, charts/pega/config/prlog4j2.xml, charts/pega/license.md, charts/pega/requirements.yaml, charts/pega/templates/_helpers.tpl, charts/pega/templates/_pega-config.tpl, charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/_pega-ingress.tpl, charts/pega/templates/_pega-service.tpl, charts/pega/templates/eks/pega-ebs-storage-class.yaml, charts/pega/templates/pega-batch-config.yaml, charts/pega/templates/pega-batch-deployment.yaml, charts/pega/templates/pega-database-secret.yaml, charts/pega/templates/pega-environment-config.yaml, charts/pega/templates/pega-registry-secret.yaml, charts/pega/templates/pega-search-deployment.yaml, charts/pega/templates/pega-search-service.yaml, charts/pega/templates/pega-search-transport-service.yaml, charts/pega/templates/pega-stream-config.yaml, charts/pega/templates/pega-stream-deployment.yaml, charts/pega/templates/pega-stream-ingress.yaml, charts/pega/templates/pega-stream-service.yaml, charts/pega/templates/pega-web-config.yaml, charts/pega/templates/pega-web-deployment.yaml, charts/pega/templates/pega-web-ingress.yaml, charts/pega/templates/pega-web-service.yaml, charts/pega/values.yaml
Initial commit of 8.2.1 Helm Charts.
=> initial commit

.gitignore, .travis.yml, Makefile, README.md, charts/pega/templates/_pega-config.tpl
Example yaml will be generated when a release is tagged.  This happens during the travis-ci build and then the archives are added to the release.  Additionally, it can be tested using _make examples_.
=> Update build process to generate example yaml

charts/pega/Chart.yaml
Fixing #13 by updating the chart version to 1.0.0
=> Adding a reasonable chart version (1.0.0)

charts/pega/templates/pega-search-deployment.yaml, charts/pega/values.yaml
1. Added requests.memory and limits.memory for Pega search deployment.
2. Added requests.memory/requests.cpu and limits.memory/limits.cpu for cassandra deployment.
=> Fixing #18 by updating CPU/Memory request/limit for cassandra and search

README.md
=> Update readme based on GCS feedback

.travis.yml, charts/pega/README.md, charts/pega/templates/_pega-service.tpl, charts/pega/templates/pega-tier-service.yaml, charts/pega/values-medium-alldetails.yaml, charts/pega/values-minimal.yaml, terratest/src/test/deployment_utility.go
changing from `NodePort` to `LoadBalancer` so the pega service gives IP Address to pega-web tiers
#28
=> change default type of service from LoadBalancer

README.md, charts/pega/README.md, charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/charts/pegasearch/values.yaml, charts/pega/values.yaml
Add documentation for .custom.env.  See #39.
=> Defining custom enviroment variables - Issue/#39

charts/pega/README.md, charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/charts/pegasearch/values.yaml, charts/pega/templates/_pega-deployment.tpl
Add support for specifying an imagePullPolicy for the pega and search images.
This fixes #56
=> Configurable imagePullPolicy

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .gitignore
Adding issue templates for bug reports and feature requests.
=> Creating a standard ISSUE_TEMPLATE

charts/pega/charts/installer/templates/pega-install-environment-config.yaml, charts/pega/charts/installer/templates/pega-upgrade-environment-config.yaml, charts/pega/templates/pega-environment-config.yaml
Check for a missing driverUri (not required) before generating. 
This fixes #50
=> Check for null driverUri

.travis.yml, terratest/src/test/Gopkg.lock, terratest/src/test/aks_deploy_test.go, terratest/src/test/constants.go, terratest/src/test/deploy_test.go, terratest/src/test/eks_deploy_test.go, terratest/src/test/install_deploy_test.go, terratest/src/test/install_test.go, terratest/src/test/invalidAction_test.go, terratest/src/test/openshift_test.go, terratest/src/test/upgrade_deploy_test.go, terratest/src/test/upgrade_test.go
Fix terratest for be able to run go test instead of using different file lists
=> Fix terratest 

charts/pega/templates/_pega-service.tpl, charts/pega/templates/pega-tier-service.yaml
Add NodePort as service type fo GKE.
=> Add NodePort as service type fo GKE.

.travis.yml, charts/pega/templates/_helpers.tpl
corrected managed certificate generation in gke
=> corrected managed certificate generation in gke

docs/Deploying-Pega-on-PKS.md
Update documentation to clarify where a PKS cluster should be sourced.
=> Remove assumptions of a provided PKS cluster

charts/pega/templates/_pega-k8s-ingress.tpl, charts/pega/templates/_pega-service.tpl
This PR is related to two recent issues both related to ingress annotations.
=> Fixing annotation bugs related to ingress changes

charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl, charts/pega/values.yaml, terratest/src/test/pega/deployment_utility.go
Changing  CPU limit as per https://github.com/pegasystems/pega-helm-charts/issues/145
=> Increase CPU limit for faster container startup

docs/building-your-own-Pega-installer-image.md
This change is for building installer image.
=> Modified readme to build installer image

charts/pega/README.md, charts/pega/charts/installer/templates/_pega-installer-job.tpl
Allow annotations for the installer pod.
=> Installer pod annotations

charts/pega/charts/pegasearch/templates/_helpers.tpl, charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/charts/pegasearch/templates/pega-search-service.yaml, charts/pega/charts/pegasearch/templates/pega-search-transport-service.yaml, charts/pega/templates/_helpers.tpl, charts/pega/templates/pega-environment-config.yaml, charts/pega/templates/pega-tier-deployment.yaml
Add support for configuring the chart to use the external search service.
=> Search service integration

charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/pega-environment-config.yaml
Pass PEGA_STREAM_URL to docker image to get changes in  https://github.com/pegasystems/docker-pega-web-ready/pull/82
Fail if both stream url and stream node type provided
=> Provide Stream Service support through env var

Jenkinsfile, Makefile, charts/addons/requirements.yaml
This is to address #219 
https://helm.sh/blog/charts-repo-deprecation/
=> ISSUE-219 Update addons dependency chart repos

charts/pega/templates/_pega-eks-ingress.tpl, terratest/src/test/pega/pega-tier-ingress_test.go
changes to update default ALB routing algorithm in AWS
=> ISSUE-223 changes to update default ALB routing algorithm in AWS

charts/pega/charts/hazelcast/templates/pega-hz-environment-config.yaml
Added cluster size field to the hz config map
=> BUG-616595 Add cluster size to hz configmaps

charts/pega/templates/_pega-credentials-secret.tpl, charts/pega/templates/pega-environment-config.yaml, charts/pega/values.yaml, terratest/src/test/pega/pega-credentials-secret-with-cassandra-enc_test.go, terratest/src/test/pega/pega-credentials-secret_test.go
Expose settings being added to the underlying image in pegasystems/docker-pega-web-ready#110
=> Expose settings for Cassandra encryption

charts/backingservices/values.yaml
Increased ES default resource configuration to match dev environment loads
=> ISSUE-88242 Increased ES default resource config

docs/Deploying-Pega-on-GKE.md
**Database version**, select **PostgreSQL 11 or 12**
=> US-395237 - Update GCP doc with PG v12 Support

charts/pega/README.md, charts/pega/templates/_pega-config.tpl, charts/pega/templates/_pega-credentials-secret.tpl, charts/pega/templates/pega-environment-config.yaml, charts/pega/values.yaml, terratest/src/test/Gopkg.lock, terratest/src/test/pega/data/expectedInstallDeployWeb.xml, terratest/src/test/pega/data/pega-tier-config-override_values.yaml, terratest/src/test/pega/pega-credentials-secret-with-cassandra-enc_test.go, terratest/src/test/pega/pega-tier-config-override_test.go, terratest/src/test/pega/pega-tier-config-web_test.go
* Allow overrides of Tomcat's server.xml and web.xml
* server.xml default copy included from config/deploy if no override is provided
* No web.xml default is provided, but will be picked up if a copy is placed in config/deploy
* web.xml is not included if no override is provided and the file does not exist in config/deploy
=> Allow server.xml and web.xml overrides in tier configmaps

charts/pega/README.md, charts/pega/templates/_pega_hpa.tpl, charts/pega/values-large.yaml, charts/pega/values.yaml, terratest/src/test/pega/data/pega-tier-config-override_values.yaml, terratest/src/test/pega/data/values_hpa_disabletarget.yaml, terratest/src/test/pega/data/values_hpa_overridevalues.yaml, terratest/src/test/pega/pega-tier-hpa_test.go
Adjusting default scaling behavior based on performance feedback
=> Adjust scaling

.travis.yml, before_deploy.sh
=> Ragsnsbintraytogithubautomation

charts/pega/charts/installer/config/prpcUtils.properties.tmpl, terratest/src/test/pega/data/expectedPRPCUtils.properties.tmpl
Expose custom jvm args option in prpcUtils.properties to provide any specific arguments in runtime
=> TASK-1142653 Added custom jvm args

README.md
Updating all repository configuration from travis-ci.org to travis-ci.com.
=> Update to travis-ci.com

charts/pega/templates/_helpers.tpl, charts/pega/templates/_pega-deployment.tpl
If privateHostedZoneDomainName is present, we construct the dnsConfig annotations for private hosted zones
=> US-422536 (Allow Infinity to DNS lookup local HZ)

README.md, docs/Deploying-Pega-on-openshift.md
Update the documentation to clarify the current supported OpenShift options.
=> Clarify OpenShift Support Documentation

.travis.yml
=> Replace travis credentials.

charts/pega/config/deploy/context.xml.tmpl, terratest/src/test/pega/data/expectedInstallDeployContext.xml.tmpl
Remove the JNDI binding that sets `prconfig/database/drivers` so that it can be set by configuring Data-Admin-System-Setting Pega-EngineCode.prconfig/database/drivers instead.
=> Remove database driver class JNDI setting from context.xml template.

.travis.yml
=> Updated travis credentials.

charts/pega/config/deploy/server.xml.tmpl, terratest/src/test/pega/data/expectedInstallDeployServer.xml.tmpl
explicitly setting maxHeaderCount to default (100)
=> BUG-747293 (set maxHeaderCount to default (100))

charts/pega/KafkaClusterRequirement.md
KafkaClusterRequirement.md - updated with external birnami kafka example under TASK-1364387 in US-506379
=> Update KafkaClusterRequirement.md 

charts/pega/charts/installer/templates/pega-install-environment-config.yaml, terratest/src/test/pega/pega-install-environment-config_test.go
=> Remove duplicate DB_TYPE entry.

charts/pega/README.md, charts/pega/values.yaml
ISSUE-109438 - Document running Pega without Cassandra
=> ISSUE-109438 - Document running Pega without Cassandra

charts/pega/templates/_helpers.tpl, charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/_pega-kerberos.tpl, charts/pega/templates/pega-kerberos-config.yaml, charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml, terratest/src/test/pega/data/values_with_kerberos.yaml, terratest/src/test/pega/data/values_without_kerberos.yaml, terratest/src/test/pega/pega-tier-deployment-with-and-without-kerberos_test.go
Added support for mounting krb5.conf file - Decisioning use-case
=> Added support for mounting krb5.conf

charts/pega/README.md
Updated Clustering Service Docker images versions to the latest available.
=> BUG-794750 - Update Clustering Service versions

charts/pega/charts/hazelcast/templates/clustering-service-deployment.yaml
BUG-798826: External Image Pull Secrets
=> BUG-798826: External Image Pull Secrets

charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml
BUG-752454: Updated values.yaml for hazelcast section
=> BUG-752454: Updated values.yaml for hazelcast section

charts/backingservices/charts/srs/README.md
Updated SRS image version to 1.21.1 in README.md
=> Updated SRS image version to 1.21.1 in README.md

charts/pega/templates/_helpers.tpl, charts/pega/templates/pega-provider-validate.yaml, terratest/src/test/pega/pega-provider-validate_test.go
=> validate the value given for provider

charts/pega/charts/installer/templates/_helpers.tpl, terratest/src/test/pega/utilities.go
Make sure the k8s-wait-for params are set for all k8s providers.
=> Wait for config fix

charts/pega/charts/hazelcast/templates/_supplemental.tpl, charts/pega/charts/installer/templates/_helpers.tpl, charts/pega/charts/installer/templates/_supplemental.tpl, charts/pega/charts/pegasearch/templates/_helpers.tpl, charts/pega/charts/pegasearch/templates/_supplemental.tpl, charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/templates/_helpers.tpl, charts/pega/templates/_supplemental.tpl, terratest/src/test/pega/utilities.go
This is to ensure pega-helm-charts works fine when we have resource quota defined per namespace.
=> Feature/us 561435 - Init container to have cpu and memory limits defined.

charts/pega/charts/installer/config/prpcUtils.properties.tmpl, charts/pega/charts/installer/config/setupDatabase.properties.tmpl, terratest/src/test/pega/data/expectedPRPCUtils.properties.tmpl, terratest/src/test/pega/data/expectedSetupdatabase.properties
Added default(4gi) max heap space
=> ISSUE-117022: Set default max heap space for installer and import utility

charts/pega/README.md, charts/pega/templates/_pega-openshift-ingress.tpl
=> implement ingress.annotations for openshift

charts/pega/templates/_pega-pdb.tpl, charts/pega/templates/_pega_hpa.tpl, terratest/src/test/pega/data/values_hpa_custom_label.yaml, terratest/src/test/pega/data/values_pdb_custom_labels.yaml, terratest/src/test/pega/pega-tier-hpa_test.go, terratest/src/test/pega/pega-tier-pdb_test.go
Support custom labels for tier HPA and PDB resources.
=> Support custom labels for HPA and PDB

charts/pega/Ephemeral-web-tier-values.yaml, charts/pega/config/deploy/prconfig.xml, terratest/src/test/pega/data/expectedInstallDeployPrconfig.xml
Removed security/urlaccessmode configuration as it is no longer applicable
=> BUG-830220 : Removed unwanted prconfig setting

charts/pega/charts/hazelcast/values.yaml, terratest/src/test/pega/clustering-service-environment-config_test.go
BUG-808734 : HZ GC setting updated
=> BUG-808734 : HZ GC setting updated

README.md, charts/pega/README.md, docs/patching-pega-deployment.md
Removed references to Pega Platform 8.2, as we only support 8.3+
=> BUG-841263 (CMC only supported from 8.3+)

charts/backingservices/charts/srs/README.md
1. Remove support of 7.16.3 with K8s >= 1.25
2.  Minor adjustments to authentication information
=> Updates to SRS ReadMe 

charts/pega/charts/hazelcast/templates/clustering-service-pdb.yaml, charts/pega/charts/hazelcast/templates/pega-hz-pdb.yaml
BUG-851649 : Pod distribution budget added to clustering service
=> BUG-851649 : Pod distribution budget added to clustering service

charts/pega/README.md, charts/pega/templates/_pega_hpa.tpl, charts/pega/values-large.yaml, charts/pega/values.yaml, terratest/src/test/pega/data/values_hpa_behavior.yaml, terratest/src/test/pega/pega-tier-hpa_test.go
1: changes made to HorizontalPodAutoscaler to support stabilization window during scaling
2: changes made to readme file usage instructions
3: Reported github issue https://github.com/pegasystems/pega-helm-charts/issues/676
=> US-598110: Provide stabilization window feature to hpa during scaling to avoid flapping issue

charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/charts/pegasearch/values.yaml, charts/pega/templates/_pega-deployment.tpl, charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml, terratest/src/test/pega/pega-deployment-topology-spread-constraints_test.go
Added topology spread constraints and pod labels configuration in values.yaml
Specified the same topology spread configuration for the deployments and statefulsets.
=> US-598183: Support for Topology Spread Constraints

charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml
Pega recommended replication value is 3.
=> Bug 868785 : Replication factor value updated to 3.

charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl, charts/pega/values-large.yaml, charts/pega/values.yaml, terratest/src/test/pega/pega-tier-deployment-tolerations_test.go
Added an option to configure toleration for workloads
=> US-612844: Added toleration configuration for workloads

charts/backingservices/charts/constellation-messaging/templates/messaging-deployment.yaml, charts/backingservices/charts/constellation-messaging/values.yaml, charts/backingservices/charts/constellation/templates/clln-deployment.yaml, charts/backingservices/charts/constellation/templates/clln-ingress.yaml, charts/backingservices/charts/constellation/values.yaml
TASK-1632399: fix container vul. for appstatic and messaging services
=> TASK-1632399: fix container vul. for appstatic and messaging services

charts/backingservices/charts/srs/README.md, charts/backingservices/values.yaml
This PR fixes vulnerabilities related to Alpine Docker Image.
=> Release SRS 1.31.8 for fixing vulnerabilities

.github/workflows/github-actions-build.yml, charts/addons/Chart.yaml, charts/backingservices/Chart.yaml, charts/pega/Chart.yaml
Fix chart version to tag synchronization.
Tags arte currently 1 behind release tag.
=> Fix chart version to tag synchronization.

charts/addons/README.md
Fixed the broken link to add-on chart values.yaml
=> Update README.md - fixed the broken link

charts/pega/charts/installer/templates/_helpers.tpl, charts/pega/charts/installer/templates/_pega-installer-job.tpl
Adding job labels to the installer template so there is the ability to add labels via the infinity service
=> US-648252 added job labels to the installer template

charts/backingservices/charts/srs/README.md
From: Meka, Ravi Teja <RaviTeja.Meka@in.pega.com> 
Sent: Wednesday, April 9, 2025 7:45 AM
Cc: SearchXScrumTeam <SearchXScrumTeam@pega.com>; Reddy, Srinivas <Srinivas.Reddy2@in.pega.com>
Subject: New version update for SRS: 1.37.9
Hi Kinga,
Requesting you to update the SRS version to 1.37.9 in Pega documentation & helm chart documentation.
This version contains vulnerability fixes in SRS image & critical bug fix (BUG-920092) .
Thanks,
Ravi Teja Meka.
=> BUG-920795 - [CMC] SRS 1.37.9 version update
