pegasystems/pega-helm-charts

charts/pega/templates/pega-environment-config.yaml
When Cassandra was not deployed, the CASSANDRA_NODES field is missing rather than empty.  It should be present because the batch tier depends on it being referenced as an env variable.
=> Fix problem deploying without cassandra

README.md, charts/pega/README.md, charts/pega/charts/pegasearch/templates/pega-search-deployment.yaml, charts/pega/charts/pegasearch/values.yaml, charts/pega/templates/_pega-openshift-ingress.tpl, charts/pega/templates/pega-environment-config.yaml, charts/pega/templates/pega-tier-deployment.yaml
* Updates for Helm 3 #34 .
* Readme now references bintray repo and the *getting started* section no longer requires a repo clone.
* API references updated to support Kubernetes 1.16.x. #27 
* Fixed host name mapping for OpenShift's route
* Converted several sections to be parameterized
* Added pegasearch.set_vm_max_map_count - Elasticsearch requires vm.max_map_count to be configured to an appropriate value.  This may be configured manually on your system and if so, you may bypass this privileged init container. For more information, see the [ElasticSearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html).  This value defaults to **true**.
* Added pegasearch.runAsUser - Specify a user to run as.  This is helpful in locked down …
=> Helm 3 / Kubernetes 1.16.x

charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl
Per #37 , deploymentStrategy should not be used when a volumeClaimTemplate is defined.
* Update documentation to clarify mutual exclusion with the two parameters.
* Add a clear error message on deployment by checking to see if the current tier is a Deployment before including the strategy details.
=> deploymentStrategy should not be used with volumeClaimTemplate #37

charts/pega/templates/_pega_hpa.tpl, terratest/src/test/deployment_utility.go
This fixes the broken auto-scaler caused due to the HPA template still using a deprecated API Version. 
This fixes #47.
=> Fixes apiVersion for pega_hpa template to support Kubernetes v1.16.x.

charts/pega/README.md, charts/pega/templates/_pega-k8s-ingress.tpl, charts/pega/templates/_pega-service.tpl, charts/pega/templates/pega-tier-service.yaml
As a user of the Pega Helm charts, I want to be able to specify custom annotations for unique load balancer configurations without needing to extend the charts.
Annotations should be settable for services and ingresses as those are frequently used for for custom configurations.
ElasticSearch provides similar configuration as a model for both service and ingress.
This fixes #63 .
=> Add support for custom service and ingress annotations

charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/_pega-openshift-ingress.tpl
@dcasavant Like we discussed in issue #57 I made an PR with our changes we made to the template files of the Pega Helm chart. The other changes we made are within the values file so this isn't any problem.
The change I commited to the _pega-deployment.tpl can also be done accomplished by adding an custom enviroment variable to every tier within the values file. But in my opinion this is an option everyone should be able to use by default so thats why I added it to the template file.
Please let me know your opinion of the changes I made within is PR.
=> Pegabasis custom changes to template files

charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/pega-tier-deployment.yaml
Passed Tier of a node to prpc so that it can be used in admin studio. The NODE_TIER variable is set in setenv.sh file of docker. 
Passed two DSS settings to prpc so that,
1) Requestor pools can be disabled by default in pega, and 
2) Admin studio can display information without node ids
=> Introduced tier name and kubernetes specific DSS settings 

charts/pega/README.md, charts/pega/templates/_helpers.tpl, charts/pega/templates/_pega-deployment.tpl, terratest/src/test/deployment_utility.go
[Probes are used by Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) as a way to determine if an application is healthy.  They may be configured for liveness to determine if a Pod has entered a broken state, or for readiness to determine if the application is available to be exposed.  Probes may be configured for each tier independently.  If not explicitly configured, default probes will be used.  The following parameters may be used as part of a `livenessProbe` or `readinessProbe` configuration.
Parameter           | Description    | Default value
---                 | ---            | ---
`initialDelaySeconds` | Number of seconds after the container has started before liveness or readiness probes are initiated. | `300` …
=> Add support for probe configuration Issue/#65

docs/prepping-local-system-runbook-linux.md
The intention of this first step is to download the script, which we will execute in step 3. Therefore there is no need to use sudo for it, nor to pipe it to bash.
=> Correct curl command to download helm installer

charts/pega/README.md
It was recently reported that providers do not work correctly if they are all uppercase.  Updating the documentation to indicate that they are case-sensitive and should be lowercase.
=> Add note about case sensitivity

.github/CODEOWNERS
I suggest creating a team for documentation code owners. For now, just added @taz-mon.
=> Example of CODEOWNERS file.

charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/_pega-eks-ingress.tpl, charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml
This change for internal pega helm usage in EKS cluster to evict a pod during autoscaling.
The default has been set to true in-line with the behaviour had the annotation not been set.
=> Custom Annotations

charts/pega/templates/pega-gke-backend-config.yaml
This PR is to address [ISSUE-135](https://github.com/pegasystems/pega-helm-charts/issues/135)
In GKE, overriding health check of load balancer (specifically Stream) to use Platform ping service. This fix require GKE version to be 1.17.6-gke.11 or higher. Ref. [ingress-features](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features).
This change does not introduce regression if deployed on lower versions than 1.17.6-gke.11.
=> ISSUE-135: Overriding health checks for web and stream load balancers

charts/pega/charts/installer/templates/_pega-installer-job.tpl, charts/pega/charts/installer/values.yaml
Fixes #177 
Previously, running the install or upgrade action would exit helm as soon as all resources were deployed, not when the job was completed. Adding these hooks causes helm to wait until the resources are fully deployed. Note that we can only include install and upgrade (and not any deploy-related action) because otherwise we have a cyclical dependency (post-install hook + waiting for install to complete).
=> ISSUE-177 Add helm hook to force helm to wait until the install is complete

charts/addons/values.yaml
Here, default environment variables are specified for AWS authentication. But Authentication can be done in other ways without specifying these env variables. 
The default behaviour of helm is to merge the Map values of user-given(using --values or --set) and default values.
So, If we leave the **extraEnv** with some values, these values always will be there in the deployment which is unnecessary and cause other problems.
=> make default environment variables as empty in aws-alb-ingress-controller

charts/pega/charts/installer/templates/_pega-installer-job.tpl
Originally the annotations were placed on the job rather than on the pod -- this PR moves them to the pod.
=> Put the annotations on the pod template rather than on the job.

charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl
In FNX all deployments need `serviceAccountName: pega-infinity-sa` to communicate with backing-services. Currently no way to set that.
=> option to include serviceAccountName in deployments

Jenkinsfile, charts/addons/README.md, charts/addons/requirements.yaml, charts/addons/values.yaml, charts/pega/requirements.yaml, charts/pega/templates/_pega-service.tpl, charts/pega/templates/pega-tier-ingress.yaml, terratest/src/test/addons/alb-ingress_test.go
Travis builds are failing with https://travis-ci.org/github/pegasystems/pega-helm-charts/builds/751186081 chart not found in corresponding repo issues.
Downloading traefik from repo https://charts.helm.sh/stable
Save error occurred: could not find : chart aws-alb-ingress-controller not found in https://kubernetes-charts-incubator.storage.googleapis.com/
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart aws-alb-ingress-controller not found in https://kubernetes-charts-incubator.storage.googleapis.com/
Makefile:2: recipe for target 'dependencies' failed
make: *** [dependencies] Error 1
The command "make dependencies" exited with 2.
To Reproduce:
Perform helm dep update and check if dependencies are downloaded properly using "helm dep list" under …
=> Update cassandra and ALB chart repo to use latest migrated repository

charts/pega/README.md, charts/pega/RecommendedJVMArgs.md, charts/pega/templates/_helpers.tpl, charts/pega/values-large.yaml, terratest/src/test/pega/pega-tier-deployment_test.go
For better tunability of JVM Pega recommends defaults for some of the JVM arguments. Any JVM arguments with the flexibility to override can be provided as **catalinaOpts** under a specified tier. Note that _some_ of the arguments don't have the flexibility to be overridden and hence are defaulted in Docker image. This is complemented by related changes for **CATALINA_OPTS** in https://github.com/pegasystems/docker-pega-web-ready image. 
Link to the mentioned PR: https://github.com/pegasystems/docker-pega-web-ready/pull/95
=> Added the recommended default JVM arguments as CATALINA_OPTS

before_deploy.sh
As reported in #234 we are no longer publishing the addons file.  It appears that this may be caused by `before_deploy.sh` applying the same index to both addons and then backingservices to replace the descriptor-template.json with the actual file names.
This PR attempts to fix the publishing of the addons chart by updating the before deploy script with a proper index for the backing services tgz.
=> Fix indexing of the backing services file name

charts/backingservices/charts/srs/templates/srsservice_service.yaml, terratest/src/test/backingservices/srs-service_test.go
Bug identified with service availability on port 8080 only. The documentation does not specify port 8080 and should be accessible using http://srs-service-name
=> BUG-629910 SRS service http port mapping to 80

charts/pega/config/deploy/context.xml.tmpl, charts/pega/templates/pega-environment-config.yaml, terratest/src/test/pega/data/expectedInstallDeployContext.xml
RO datasource is added with presence of new global.jdbc.readerurl value, and configured with RO env var credentials. This is to support [QueryRunner](https://community.pega.com/knowledgebase/articles/pega-cloud/query-runner-landing-page-testing-select-statements)
=> Add opt-in ReadOnly datasource to context.xml template

charts/pega/README.md, charts/pega/templates/_helpers.tpl, charts/pega/templates/_pega-deployment.tpl, charts/pega/values-minimal.yaml, charts/pega/values.yaml, terratest/src/test/pega/data/pega-tier-config-override_values.yaml, terratest/src/test/pega/data/values_gke_managedcertificate.yaml, terratest/src/test/pega/pega-tier-deployment_test.go
Adjust the JVM and container memory settings to reduce the risk of inadvertently exceeding the container memory limit.
=> Adjust chart memory limits to mitigate oom risk

.travis.yml, charts/pega/templates/_pega-deployment.tpl, terratest/src/test/pega/pega-tier-deployment_test.go
Resolves #270 
The port change to 8081 should not have been made in a patch release in combination with the ability to update server.xml.
Use 8080 and release a new patch release to resolve the issue, then follow up after with a new minor version for 8081 which also details the minimum docker-pega-web-ready image requirements.
=> Issue #270 Don't swap the 8080 port in a patch release

docs/Deploying-Pega-on-AKS.md, docs/Deploying-Pega-on-EKS.md, docs/Deploying-Pega-on-GKE.md, docs/Deploying-Pega-on-PKS.md
Updated runbook docs for Helm chart assets being moved from bintray to github.
=> bintray assets to github doc updates for runbooks

charts/pega/config/deploy/server.xml, terratest/src/test/pega/data/expectedInstallDeployServer.xml
Updated 8080 connector in server.xml to use the following, for parity with cuttyhunk:
* protocol=org.apache.coyote.http11.Http11Nio2Protocol
* relaxedQueryChars="[ ]"
* relaxedPathChars="[ ]"
* maxHttpHeaderSize=16384
* maxSavePostSize=65536
=> US-408948 (Update CloudK Connector settings)

charts/pega/RecommendedJVMArgs.md
These require additional investigation before we recommend them
=> Remove currently undesired recommendations

charts/pega/README.md
I'm not really sure when this changed but if we use `docker.pega.image: "pegasystems/pega"` in a Pega 8.4.x setup, it no longer works and the pods fail during bootstrap with the following exception:
```
24-May-2021 10:10:06.589 SEVERE [http-nio-8080-exec-5] com.pega.pegarules.internal.bootstrap.PRBootstrap. Unable to retrieve method
java.lang.NoSuchMethodException: com.pega.pegarules.web.impl.WebStandardImpl.doPostInner(com.pega.pegarules.internal.bootstrap.interfaces.IWebStandard, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
```
This is because Kubernetes implicitly pulls the `:latest` tagged image and this seems to have been updated to Pega 8.6 sometime recently and this image is no longer compatible with Pega 8.4.x databases.
I thought it was important …
=> Adds note to improve document about Pega Docker image versions in DockerHub.

terratest/run-tests-from-cmdline.md, terratest/run-tests-with-intellij.md
As of Go v1.16, the environment variable GO111MODULE is set to on by default. Since the tests rely on GOPATH instead of modules, you have to set GO111MODULE to off.
I also made it explicit that to run the tests via Intellij, you have to have the Ultimate edition.
=> Update instructions for manually running terratest tests

charts/pega/charts/installer/templates/_helpers.tpl, charts/pega/charts/installer/templates/_pega-installer-job.tpl, charts/pega/charts/installer/templates/pega-installer-config.yaml, charts/pega/templates/_pega-credentials-secret.tpl, charts/pega/templates/_pega-registry-secret.tpl, terratest/src/test/pega/pega-custom-upgrade_test.go, terratest/src/test/pega/pega-installer-job_test.go
added post upgrade hook in case of upgrade
=> Add post-upgrade hook to helm installer job in case of upgrade

charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl, charts/pega/templates/_pega_hpa.tpl, terratest/src/test/Gopkg.lock, terratest/src/test/pega/pega-tier-deployment_test.go, terratest/src/test/pega/pega-tier-hpa_test.go
* Set CPU request value to 3
* Set HPA target CPU value to 2.55
* Update README to show new default values
=> Bug-657197 update CPU request value and HPA target CPU value

charts/pega/config/deploy/prlog4j2.xml, terratest/src/test/pega/data/expectedInstallDeployPRlog4j2.xml
prlog4j2.xml is out of sync w/ the version shipped by the platform. This PR adds missing PegaMobile and UsageMetrics appenders and a few related updates.
=> update prlog4j2.xml to include PegaMobile appenders and related configs

.travis.yml, charts/pega/README.md, charts/pega/templates/_pega-deployment.tpl, terratest/src/test/pega/data/values_sidecar_containers.yaml, terratest/src/test/pega/pega-custom-upgrade_test.go, terratest/src/test/pega/pega-installer-job_test.go, terratest/src/test/pega/pega-tier-deployment-with-sidecar_test.go, terratest/src/test/pega/pega-tier-deployment_test.go, terratest/src/test/pega/utilities.go
Support custom sidecar containers within a pod, adjacent to the tomcat container.
Adopts the pull request https://github.com/pegasystems/pega-helm-charts/pull/239 created by @mathijs55
=> Support custom sidecar containers in deployment spec, plus test.

charts/addons/README.md, charts/addons/requirements.yaml, charts/addons/values.yaml, terratest/src/test/addons/efk_test.go, terratest/src/test/addons/metrics-server_test.go, terratest/src/test/addons/traefik_test.go
ISSUE #376 was recently created because some of our dependencies in the addons chart were using deprecated API versions that were not in Kubernetes 1.22.  This was causing a helm install of the chart to fail.
I'm not certain we want to merge this pr yet but I though it would be a good idea to open it.   I'm hesitant because the [ingress-azure](https://github.com/Azure/application-gateway-kubernetes-ingress) chart only added K8s 1.22 support in their most recent release candidate, 1.5.0-rc1.  [There's an issue open on their project](https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1317) about releasing 1.5.0 but so far it hasn't had any positive feedback.  Apparently the GA release for AKS on K8s 1.22 uses the release candidate as well.
=> Update addons chart dependencies for Kubernetes 1.22

charts/pega/config/deploy/server.xml.tmpl, terratest/src/test/pega/data/expectedInstallDeployServer.xml.tmpl
Disable autoDeploy feature of tomcat in default config used by the chart.
=> Disable autoDeploy feature in default config.

charts/backingservices/README.md, charts/pega/README.md
These are instructions for using a private registry for the utility images, busybox and k8s-wait-for. Pega does not provide customized versions of these public images.
=> fix heading for busybox/k8s-wait-for image configuration doc

charts/pega/README.md, charts/pega/charts/installer/templates/_helpers.tpl, charts/pega/values-large.yaml, charts/pega/values-minimal.yaml, charts/pega/values.yaml, terratest/src/test/pega/data/values_http_disabled.yaml, terratest/src/test/pega/data/values_with_overidden_liveness_probe_config.yaml, terratest/src/test/pega/utilities.go
This PR switches from dcasavant/k8s-wait-for to the pegasystems/k8s-wait-for docker image.
The new image includes additional support for retrying queries to the API server which we have observed on occasion in a subset of our supported cloud providers.
This PR also fixes the rendering of k8s-wait-for initcontainers such that they correctly honor the global.utilityImages.k8s_wait_for.waitTimeSeconds property.
=> Use pegasystems/k8s-wait-for image for job ordering 

charts/pega/README.md
This change adds information about Pega not supporting separate charts for different tiers in a single deployment to the Tiers of a Pega deployment section.
=> BUG-718978 - Added single helm chart requirement

charts/backingservices/charts/srs/templates/srsservice_deployment.yaml, terratest/src/test/backingservices/srs-deployment_test.go
**Fixes:**
- Fixed SRS Deployment issue incase of externally managed Elasticsearch server when deployed with no basic authentication. (Issue #548)
- Removed Duplicate ENV Variable `ELASTICSEARCH_AUTH_PROVIDER` while deploying SRS.
=> ISSUE-548: Fixed SRS Deployment for Ext ES

docs/upgrading-pega-deployment-zero-downtime.md
Added a note recommending the use of the latest Helm version and Helm chart release when updating Pega Platform.
=> BUG-798792 - Using latest Helm charts during update

charts/pega/templates/_pega-service.tpl, charts/pega/values.yaml, terratest/src/test/pega/data/values_with_servicetype.yaml, terratest/src/test/pega/pega-tier-service-with-servicetype_test.go, terratest/src/test/pega/pega-tier-service_test.go
Added the capability to specify the service type. Also added a capability to restrict access to specific IP CIDR blocks in case of a LoadBalancer service type.
=> US-512993 : Adding the capability to configure servicetype.

charts/backingservices/charts/srs/README.md, charts/backingservices/values.yaml
Added clarity about when to use srs.enabled=true following documentation BUG-822852.
=> [BUG-822852] Add clarity to SRS Readme.md

charts/pega/charts/hazelcast/values.yaml, terratest/src/test/pega/clustering-service-environment-config_test.go
Updated Hazelcast heap setting to derive from available RAM
Changed the literal value to % so that it can be derived based on provided memory to the container.
Default from HZ : https://github.com/hazelcast/hazelcast-docker/blob/master/hazelcast-enterprise/Dockerfile#L16
=> Updated Hazelcast heap setting to derive from available RAM

charts/backingservices/charts/srs/README.md
US-583096 : Updated SRS docker image version from 1.25.3 to 1.28.0 which contains changes related to base docker image. This base docker image (Alpine) supports ES data nodes more than 64, which was a limitation earlier.
=> US-583096 : Updated SRS Docker Image version from 1.25.3 to 1.28.0

charts/backingservices/charts/srs/README.md, charts/backingservices/charts/srs/templates/_helpers.tpl, charts/backingservices/values.yaml
Helm chart and documentation updates for updating to elasticsearch 8.x version
=> US-530858: Helm chart and documentation updates for updating to elasticsearch 8.x version

charts/pega/charts/installer/templates/pega-installer-pdb.yaml
In some scenarios install charts may be deployed twice, once for install and once for upgrade. This leads to a conflict on the installer PDB which is used for both.
This PR makes the PDB a hook to avoid that conflict.
=> make installer PDB a hook to avoid conflicts with upgrade jobs

charts/backingservices/charts/constellation/templates/clln-ingress.yaml
Fixed indentation in file: clln-ingress.yaml in order to allow custom ingress annotations (the old implementation had 4 extrra spaces with did not allow to add more than one custom configurations)
=> Fixed indentation problem with constellation chart with custom ingress annotations

.github/workflows/github-actions-stale.yml
increase operations-per-run for stale action bot as default 30  exceeding the limit and operations are exiting with (No more operations left! Exiting...)
=> BUG-879464: increase operations-per-run for stale action bot as default 30 is not sufficient

terratest/src/test/pega/pega-installer-job_test.go
Add test for including ephemeral storage requirement to the install job.
=> Add test for including ephemeral storage requirement to the install job.

charts/pega/templates/_pega-deployment.tpl, charts/pega/values.yaml, terratest/src/test/pega/pega-tier-deployment_container_security_context_test.go
Allow to configure securityContext for Pega tier containers to specify security settings for a Container, include the securityContext field in the Container manifest.
Note that the Security settings that you specify for a Container apply only to the Pega container, and they override settings made at the Pod level when there is overlap. Container settings do not affect the Pod's Volumes.
See, https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
=> US-625432 Configure securityContext for Pega containers

docs/Deploying-Pega-on-EKS.md
Advise to choose an instance type that meets client's and Pega's requirements instead of recommending a specific type.
=> BUG-826731 - Remove db.m5.large DB instance recommendation

.github/workflows/mend-scan.yml
Fix the mend scan which was failing due to referencing a deprecated version of the upload artifact action.
=> Update deprecated gh action.

charts/backingservices/charts/srs/templates/_helpers.tpl, charts/backingservices/values.yaml
US-641138: Updated srs backingservice helm chart to support both Elasticsearch & OpenSearch
As of today, SRS values.yaml has fields that supports only Elasticsearch. With these new changes, SRS will work on both Elasticsearch & OpenSearch
=> US-641138: Updated srs backingservice helm chart to support both Elasticsearch & OpenSearch 

charts/pega/README.md
From: Peterson, John <John.Peterson@pega.com> 
Sent: Friday, November 15, 2024 4:10 PM
Cc: Casavant, Dave <Dave.Casavant@pega.com>; Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Talbot, Adam <Adam.Talbot@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Subject: CMC Documentation clarification for SRS & Databases.
Hi Kinga, 
Yes, I agree with your proposed changes.  
Thanks!
John
From: Kowalska, Kinga <Kinga.Kowalska@pega.com> 
Sent: Thursday, November 14, 2024 8:15 AM
To: Peterson, John <John.Peterson@pega.com>
Cc: Casavant, Dave <Dave.Casavant@pega.com>; Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Talbot, Adam <Adam.Talbot@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Subject: …
=> BUG-898033 - Documentation clarification for DB support

charts/backingservices/charts/srs/README.md
From: Peterson, John <John.Peterson@pega.com>
Sent: Friday, November 15, 2024 4:10 PM
Cc: Casavant, Dave <Dave.Casavant@pega.com>; Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Talbot, Adam <Adam.Talbot@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Subject: CMC Documentation clarification for SRS & Databases.
Hi Kinga,
Yes, I agree with your proposed changes. 
Thanks!
John
From: Kowalska, Kinga <Kinga.Kowalska@pega.com>
Sent: Thursday, November 14, 2024 8:15 AM
To: Peterson, John <John.Peterson@pega.com>
Cc: Casavant, Dave <Dave.Casavant@pega.com>; Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Talbot, Adam <Adam.Talbot@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Subject: RE: …
=> BUG-898031 SRS Readme clarification on embedded ES

README.md, charts/backingservices/charts/constellation-messaging/README.md, charts/backingservices/charts/constellation/README.md, charts/pega/README.md, docs/Deploying-Pega-on-AKS.md, docs/Deploying-Pega-on-EKS.md, docs/Deploying-Pega-on-GKE.md, docs/Deploying-Pega-on-PKS.md, docs/Deploying-Pega-on-openshift.md, docs/building-your-own-Pega-installer-image.md, docs/patching-pega-deployment.md, docs/upgrading-pega-deployment-zero-downtime.md
Many links to Pega Community forward the user to the docs-previous page that is being decommissioned.
=> US-654940 - Remove docs-previous links from github readmes

README.md, charts/backingservices/charts/srs/README.md
Added link to https://docs.pega.com/bundle/platform/page/platform/deployment/client-managed-cloud/pega-docker-images-manage.html#ariaid-title5 as requested.
From: Peterson, John <John.Peterson@pega.com> 
Sent: Tuesday, April 8, 2025 1:37 PM
Subject: Build custom Pega images
Hi Kinga,
I have some feedback on this documentation:  https://docs.pega.com/bundle/platform-88/page/platform/deployment/client-managed-cloud/pega-docker-images-manage.html#ariaid-title5
1)	The section title should be renamed to “Build your own custom Pega images” since it describes how to do it for the Installer, Runtime, and Search images, and not just the installer.
2)	“Your organization must may enforce a corporate standard as to the operating system and Java libraries …
=> [BUG-920600] Build custom Pega images

charts/backingservices/charts/srs/README.md, charts/backingservices/values.yaml
Made documentation changes following the request below:
From: Meka, Ravi Teja <RaviTeja.Meka@in.pega.com> 
Sent: Monday, May 12, 2025 9:25 AM
Cc: SearchX <SearchX@pega.com>
Subject: SRS Version update: 1.38.2
Hi [@Kowalska, Kinga](mailto:Kinga.Kowalska@pega.com),
We released new SRS version: 1.38.2 with latest vulnerabilities fixed. Kindly update the documentation.
In addition to above, I have below suggestions for documentation update based on the EA requests we received this sprint:
1.	We need to update documentation, that Pega supports only official docker images of Elasticsearch and OpenSearch, custom images like [bitnami/elasticsearch](https://github.com/bitnami/containers/blob/main/bitnami/elasticsearch/README.md) are not officially …
=> BUG-926651 - SRS documentation changes 

charts/pega/charts/installer/config/prpcUtils.properties.tmpl
CRM requires a higher heap, updated from previous minimum of 4gb to 8gb
=> BUG-909894: prpcUtils default heap may be too low

charts/backingservices/charts/srs/README.md
Update supported Elasticsearch versions and the search-n-reporting-service-os information.
=> [BUG-943397 BUG-919539] Update the compatibility matrix

charts/pega/charts/installer/config/setupDatabase.properties.tmpl, charts/pega/charts/installer/templates/_helpers.tpl, charts/pega/charts/installer/templates/_pega-environment-config.tpl, charts/pega/charts/installer/values.yaml, terratest/src/test/pega/data/expectedSetupdatabase.properties, terratest/src/test/pega/pega-install-environment-config_test.go, terratest/src/test/pega/pega-installer-job_test.go, terratest/src/test/pega/pega-upgrade-environment-config_test.go
This PR increases the default memory request/limit for the Pega installer from 5Gi/6Gi to 12Gi/12Gi.
Correspondingly, the maximum java heap for the installer was increased from 4g to 8g.
=> Increase installer memory requirements and installer heap size.
